apiVersion: apps/v1
kind: Deployment
metadata:
  name: jlapp-pedido-deployment
spec:
  selector:
    matchLabels:
      app: jlapp-pedido
  replicas: 1
  template:
    metadata:
      labels:
        app: jlapp-pedido
    spec:
      containers:
      - name: jlapp-pedido
        image: testeluismatos/jlapp-pedido-eks:latest
#        imagePullPolicy: Never
        ports:
        - containerPort: 8070
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8070
          initialDelaySeconds: 25
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8070
          initialDelaySeconds: 35
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 20
        env:
          - name: JAVA_OPTS
            value: "-server -Xmx1024M -Xms512M -Xss128m -XX:+UseParallelGC -XX:MaxRAMPercentage=75 -XX:ActiveProcessorCount=2 -XX:+UnlockExperimentalVMOptions"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/db_lanchonete
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq-deployment
          - name: SPRING_RABBITMQ_PORT
            value: "5672"
          - name: SPRING_RABBITMQ_USERNAME
            value: luis
          - name: SPRING_RABBITMQ_PASSWORD
            value: teste123