apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jlapp-deployment.yaml
  - jlapp-service.yaml
  - service-account.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

images:
  - name: jlapp-pedido
    newName: jlapp-pedido
    newTag: latest
